import type { Metadata } from "next";
import "./globals.css";
import { HeaderProvider } from "./provider/header";
import { DescriptionProvider } from "./provider/description";
import { CanvasProvider } from "./provider/canvas";
import { ColorProvider } from "./provider/color";
import { ImageProvider } from "./provider/image";
import { inter, roboto, openSans, montserrat, lato, oswald, playfair, poppins, noto, robotoCond, fontOptions } from "./canvas/fonthelper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Combine all font variables into a single string to apply to the body class
  return (
    <html lang="en">
      <body>
        <CanvasProvider>
          <HeaderProvider>
            <DescriptionProvider>
              <ColorProvider>
                <ImageProvider>
                  {children}
                </ImageProvider>
              </ColorProvider>
            </DescriptionProvider>
          </HeaderProvider>
        </CanvasProvider>

      </body>
    </html>
  );
}
