import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderProvider } from "./provider/header";
import { DescriptionProvider } from "./provider/description";
import { ColorProvider } from "./provider/color";
import { ImageProvider } from "./provider/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderProvider>
          <DescriptionProvider>
            <ColorProvider>
              <ImageProvider>
                {children}
              </ImageProvider>
            </ColorProvider>
          </DescriptionProvider>
        </HeaderProvider>
      </body>
    </html>
  );
}
